<?php

namespace DV\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FotoThumbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FotoThumbRepository extends EntityRepository
{
}
