ma_main_homepage:
    path:     /
    defaults: { _controller: MAMainBundle:Main:index }

ma_main_homepage_article:
    path:     /articles/{articleId}
    defaults: { _controller: MAMainBundle:User:index }
    requirements:
        routesId: \d+

ma_main_donation:
    path:     /donation
    defaults: { _controller: MAMainBundle:Main:donation }
