ma_main_homepage:
    path:     /
    defaults: { _controller: MAMainBundle:Main:index }

ma_main_homepage_elementAjax:
    path:     /{elementType}/{elementId}
    defaults: { _controller: MAMainBundle:Main:index }
    requirements:
        elementId: \d+

ma_main_helpUs:
    path:     /helpUs
    defaults: { _controller: MAMainBundle:Main:helpUs }
